server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**, /api/teachers/**
        - id: project
          uri: lb://project-service
          predicates:
            - Path=/api/projects/**, /api/formatoa/**
        - id: evaluation
          uri: lb://evaluation-service
          predicates:
            - Path=/api/evaluations/**
        - id: document
          uri: lb://document-service
          predicates:
            - Path=/api/anteproyectos/**
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
      default-filters:
        - AddResponseHeader=X-Gateway, FIET-Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
